// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCavEtZ5py_7EqprwNAlZ5IZ8fkhai1A8A',
    appId: '1:1030142167543:android:7959a851614641c7de86f2',
    messagingSenderId: '1030142167543',
    projectId: 'flutter-kabarin-app',
    storageBucket: 'flutter-kabarin-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBTS29l8iyWyhFLbU08n5Q7euvUst9o14',
    appId: '1:1030142167543:ios:07acedf97094200ede86f2',
    messagingSenderId: '1030142167543',
    projectId: 'flutter-kabarin-app',
    storageBucket: 'flutter-kabarin-app.firebasestorage.app',
    androidClientId: '1030142167543-rneiuefh6c57mihgh0h9ku2veipngrui.apps.googleusercontent.com',
    iosClientId: '1030142167543-64pm2cjl85gmlalgnguhqtq3g4vn53uo.apps.googleusercontent.com',
    iosBundleId: 'com.example.kabarinApp',
  );

}